apiVersion: v1
kind: Service
metadata:
  name: dotnet-openshift-demo
  namespace: dotnet-demo
  labels:
    app: dotnet-openshift-demo
spec:
  selector:
    app: dotnet-openshift-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
